#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, OVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel

def myNetwork():
    net = Mininet(controller=Controller, switch=OVSSwitch)

    print("*** Adding controller")
    c0 = net.addController(name='c0')

    print("*** Adding hosts")
    h1 = net.addHost(name='h1', ip='10.0.0.1/24')
    h2 = net.addHost(name='h2', ip='10.0.0.2/24')

    print("*** Adding switches")
    s1 = net.addSwitch(name='s1')
    s2 = net.addSwitch(name='s2')
    s3 = net.addSwitch(name='s3')
    s4 = net.addSwitch(name='s4')
    s5 = net.addSwitch(name='s5')
    s6 = net.addSwitch(name='s6')

    print("*** Creating links")
    net.addLink(h1, s1)
    net.addLink(s1, s2)
    net.addLink(s2, s3)
    net.addLink(s3, s4)
    net.addLink(s4, s5)
    net.addLink(s5, s6)
    net.addLink(s6, h2)

    print("*** Starting network")
    net.build()
    c0.start()
    s1.start([c0])
    s2.start([c0])
    s3.start([c0])
    s4.start([c0])
    s5.start([c0])
    s6.start([c0])

    print("*** Running CLI")
    CLI(net)

    print("*** Stopping network")
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    myNetwork()
